def Create_File(file_Name, idade, nome):
  file = open(file_Name, "w")
  file.write("-" * 20)
  file.write("\n")
  file.write("Nome: ")
  file.write(nome)
  file.write("\n")
  file.write("Idade: ")
  file.write(idade)
  file.write("\n")
  file.write("-" * 20)
  file.write("\n")
  file.close()


def Append_InFile(file_Name, ip_address, city, region, data, horario):
  filee = open(file_Name, "a")
  filee.write("-" * 20)
  filee.write("\n")
  filee.write("Endereco IP: ")
  filee.write(ip_address)
  filee.write("\n")
  filee.write("Cidade: ")
  filee.write(city)
  filee.write("\n")
  filee.write("Estado: ")
  filee.write(region)
  filee.write("\n")
  filee.write(data)
  filee.write("\n")
  filee.write(horario)
  filee.write("\n")
  filee.write("-" * 20)
  filee.close()
